language: node_js

node_js:
  - 10
  - 8

jobs:
  include:
    - stage: test
      install: travis_retry yarn
      script: yarn test
      branches:
        except:
          - /^v\d+\.\d+\.\d+$/

    - stage: deploy
      name: "Deploy Documentation"
      cache:
        yarn: true
      install:
        - travis_retry yarn
      branches:
        only:
          - master
      script:
        - ./deploy-docs.sh
