language: node_js

node_js:
  - 10
  - 8

jobs:
  include:
    - stage: deploy
      name: "Deploy Documentation"
      cache:
        yarn: true
      install:
        - travis_retry yarn
      branches:
        only:
          - master
      script:
        - yarn deploy:docs
