language: node_js

node_js:
  - 10
  - 8

# Keeping the Bootstrap Command to link all the packages
# till the release of the actual packages.
install:
  - yarn
  - yarn bootstrap --no-ci --force-local

jobs:
  include:
    - stage: deploy
      name: "Deploy Documentation"
      cache:
        yarn: true
      install:
        - travis_retry yarn
      branches:
        only:
          - master
      script:
        - yarn deploy:docs
